CREATE TABLE MUSTERILER (MUSTERI_ID INTEGER PRIMARY KEY, AD VARCHAR(50) NOT NULL);
CREATE TABLE SIPARISLER (SIPARIS_ID INTEGER PRIMARY KEY, MUSTERI_ID INTEGER, URUN_ID INTEGER, TUTAR INTEGER NOT NULL);
CREATE TABLE URUNLER (URUN_ID INTEGER PRIMARY KEY, URUN_ADI VARCHAR(50) NOT NULL, FIYAT INTEGER NOT NULL);

INSERT INTO MUSTERILER (MUSTERI_ID, AD) VALUES (1, 'Ali Yılmaz'), (2, 'Ayşe Kaya');
INSERT INTO URUNLER (URUN_ID, URUN_ADI, FIYAT) VALUES (1, 'Laptop', 25000), (2, 'Telefon', 15000);
INSERT INTO SIPARISLER (SIPARIS_ID, MUSTERI_ID, URUN_ID, TUTAR) VALUES (1, 1, 1, 25000), (2, 2, 2, 15000), (5, 1, 2, 15000);


UPDATE URUNLER SET FIYAT=18000 WHERE URUN_ID=1;
DELETE FROM SIPARISLER WHERE SIPARIS_ID=5;


SELECT MUSTERILER.AD, URUNLER.URUN_ADI, SIPARISLER.TUTAR
FROM MUSTERILER
JOIN SIPARISLER ON MUSTERILER.MUSTERI_ID = SIPARISLER.MUSTERI_ID
JOIN URUNLER ON SIPARISLER.URUN_ID = URUNLER.URUN_ID;
