
CREATE TABLE MUSTERILER (MUSTERI_ID INTEGER PRIMARY KEY, AD VARCHAR(50) NOT NULL);
CREATE TABLE SIPARISLER (SIPARIS_ID INTEGER PRIMARY KEY, MUSTERI_ID INTEGER, URUN_ID INTEGER, TUTAR INTEGER NOT NULL);
CREATE TABLE URUNLER (URUN_ID INTEGER PRIMARY KEY, URUN_ADI VARCHAR(50) NOT NULL, FIYAT INTEGER NOT NULL);

SELECT SUM(TUTAR) FROM SIPARISLER;
SELECT COUNT(SIPARIS_ID) FROM SIPARISLER;
SELECT AVG(TUTAR) FROM SIPARISLER;

SELECT MUSTERI_ID, SUM(TUTAR) FROM SIPARISLER GROUP BY MUSTERI_ID;

UPDATE URUNLER SET FIYAT=18000 WHERE URUN_ID=1;
DELETE FROM SIPARISLER WHERE SIPARIS_ID=5;

SELECT MUSTERILER.AD, URUNLER.URUN_ADI, SIPARISLER.TUTAR
FROM MUSTERILER
JOIN SIPARISLER ON MUSTERILER.MUSTERI_ID = SIPARISLER.MUSTERI_ID
JOIN URUNLER ON SIPARISLER.URUN_ID = URUNLER.URUN_ID;
